build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/showcheap/android-ci .
#    - docker run registry.gitlab.com/showcheap/android-ci /script/to/run/tests
    - docker push registry.gitlab.com/showcheap/android-ci:latest
  only:
    - master
